### ISSUE TITLE
virtuallist-antd配合可伸缩列，sorter属性和列拖动冲突

### ISSUE THREAD

**Issue by weiblank** [crawler-django/virtuallist-antd#101]
![image](https://github.com/crawler-django/virtuallist-antd/assets/54525528/69468ca9-f256-49d8-a8f4-441f7471bc0a)
把sorter属性去掉就没事了
![image](https://github.com/crawler-django/virtuallist-antd/assets/54525528/717f8c32-f616-4708-bb8e-9b88652762cd)

**Comment by weiblank** [comment]
需要把左侧几个列冻结 再进行拖拽

**Comment by weiblank** [comment]
https://codesandbox.io/s/compassionate-elbakyan-c2f4mg?file=/index.js   这上面可以复现

**Comment by crawler-django** [comment]
是fixed 和 sort互斥了吗?  有sorted fix就失效了

**Comment by crawler-django** [comment]
你不用VList 它也有这个问题把?

**Comment by weiblank** [comment]
> 你不用VList 它也有这个问题把?

是的  transtion样式影响到的，去掉就没事了
