### ISSUE TITLE
树型表格时，重新加载数据，数据还是原来的数据。

### ISSUE THREAD

**Issue by mar105** [crawler-django/virtuallist-antd#104]
树型表格时，点表格对数据重新排序（调用的后台接口排序 20条，这时显示正常）再加载数据  显示正常，再加载数据  显示正常，
再重新搜索换了其他条件 只有 一条数据时（这时显示卡住了）数据还是原来的数据。

**Comment by mar105** [comment]
1

**Comment by mar105** [comment]
发现非树型表格也会有这问题。

**Comment by mar105** [comment]
1

**Comment by crawler-django** [comment]
有demo例子吗

**Comment by crawler-django** [comment]
你确定不是你条件切换太快， 接口返回的快慢问题?  20条的数据返回的比1条的慢, 导致页面是20条的数据?

**Comment by mar105** [comment]
怎么加你，我这有在你代码上处理的合并单元格的代码，可以对比改动加进去。
