### ISSUE TITLE
antd V3(3.24.3)貌似不行

### ISSUE THREAD

**Issue by SamWeichangyue** [crawler-django/virtuallist-antd#11]
在你的例子当中，把package.json中的antd 版本改为V3貌似就失效了

**Comment by crawler-django** [comment]
v3调到0.2.8试试,  0.2.8的VList不用传参数.
如:
```
components={VList()}
```

**Comment by crawler-django** [comment]
example: https://codesandbox.io/s/v3-example-gk82x?file=/src/index.tsx
