### ISSUE TITLE
Resize columns in VList

### ISSUE THREAD

**Issue by GeorgeCodeHub** [crawler-django/virtuallist-antd#12]
Is it possible to implement resizable columns with VList or is it too costly for performance? An example of resizing columns is in the below link.

https://stackblitz.com/edit/sf55h2--run?file=index.js

What I'm trying to do is something like this.

`components={
VList({
          height: 500
        }),
header: {
      cell: ResizableTitle,
    },
}`

**Comment by crawler-django** [comment]
example: https://codesandbox.io/s/vibrant-darkness-kvt56?file=/index.js

```
components={ ...VList({ height: 500 }), header: { cell: ResizableTitle, }, }
// remember set scrolly is 500
```

**Comment by GeorgeCodeHub** [comment]
Thank you so much!!!

**Comment by crawler-django** [comment]
u can change VList height when scrolly changed, 
like:
```
useMemo(() => {
     return {
           ...VList({ height: scrolly }),
           header: { cell: ResizableTitle, }, }
     }
}, [scrolly])
```

**Comment by crawler-django** [comment]
because table loading transform to false or true, table components will re-render. 
if u don't care, u can do this without useMemo.
