### ISSUE TITLE
Table宽度变化的时候，columns的render函数会全部重新执行，页面卡顿

### ISSUE THREAD

**Issue by izumiiAoba** [crawler-django/virtuallist-antd#16]
### 页面第一次加载
![](https://user-images.githubusercontent.com/39220621/111856502-27109600-8966-11eb-99dd-85fcc5fd853c.png)
![](https://user-images.githubusercontent.com/39220621/111856521-41e30a80-8966-11eb-9900-b6ed662ed04a.png)
### 收起侧边栏
![](https://user-images.githubusercontent.com/39220621/111856538-5b845200-8966-11eb-9a68-e42f6c2ff8af.png)
![](https://user-images.githubusercontent.com/39220621/111856544-6343f680-8966-11eb-8cd6-f042ba539da5.png)
### 代码
```js
getColumn = () => {
        const {renamingId} = this.props;
        return [
            ... ...
            {
                title:'文件名',
                key:'name',
                width:'60%',
                ellipsis:true,
                render:(text,record,index) => {
                    console.log('title')
                    return <WtFileWriteTableNameCell
                        record={record}
                        isRename={renamingId === record.id}
                        onFileOperation={this.props.onFileOperation}
                        onFolderOperation={this.props.onFolderOperation}
                        onFileClick={this.props.onFileClick}
                    />;
                },
            },
            ... ...
        ];
};
```
页面加载的时候，render执行的应该是展示出来的row个数，但是在table宽度变化的时候，需要将所有row都重新render。
会不会就是因为这个引起的页面卡顿。

**Comment by crawler-django** [comment]
是的 ant的table在宽度变化的时候, render都会变.

**Comment by crawler-django** [comment]
可以考虑防抖, 虽然会丢掉一些实时性

**Comment by izumiiAoba** [comment]
可以讲下大概的思路么？我对ant-d的表格里面的细节不是很熟，不知道要在哪里加防抖。

**Comment by crawler-django** [comment]
先设定表格的宽度(具体值), 在切换侧边栏宽度完后, 再更新表格的宽度(document.body.width - 当前侧边栏的宽度).

**Comment by crawler-django** [comment]
这样子都可以不用防抖了. 
