### ISSUE TITLE
能否支持无分页的瀑布流加载？

### ISSUE THREAD

**Issue by alienzhangyw** [crawler-django/virtuallist-antd#17]
业务需要，要大量数据（万行以上）用无限列表单页显示，因为数据量大所以需要分片加载，大佬有实现的思路吗？

**Comment by crawler-django** [comment]
你升级到v0.5.4 和 用上onReachEnd试试.
demo: https://codesandbox.io/s/reachend-wuxianjiazaixunigundong-y9nhd
