### ISSUE TITLE
Unwanted table size addition of 10 px

### ISSUE THREAD

**Issue by aleksander351** [crawler-django/virtuallist-antd#21]
On short lists, the additional 10 pixels make an unwanted white space below the table.

![virtuallist-antd-1](https://user-images.githubusercontent.com/7508670/116042473-bd735e00-a66e-11eb-951e-955916835619.jpg)

![virtuallist-antd-2](https://user-images.githubusercontent.com/7508670/116043391-e47e5f80-a66f-11eb-8901-db0e3bc670f5.jpg)

**Comment by crawler-django** [comment]
waow.... u know, I forgot if you didn't tell me.... are u designer?
v0.5.6 already fixed

**Comment by aleksander351** [comment]
Thanks for the extremely quick response. Actually a designer brought it up, yes. Thank you.
