### ISSUE TITLE
合并单元格滚动导致卡死

### ISSUE THREAD

**Issue by ttjimsen** [crawler-django/virtuallist-antd#22]
```
    {
      width: 100,
      title: '车数',
      isMerge: true,
      key: 'sameCar',
      dataIndex: 'sameCar',
      search: false,
      fixedSearch: false,
      render: (value, row, index) => {
        const obj = {
          children: value,
          props: {},
        };
        obj.props.rowSpan = row.num
        obj.children = '1车'
        return obj;
      }
    },
```
![image](https://user-images.githubusercontent.com/31235202/118109500-e2f4bb80-b413-11eb-9d7b-87f3313d78f7.png)

合并单元格，会导致无法滚动的情况，请问怎么回事？

**Comment by crawler-django** [comment]
不要在虚拟列表做合并单元格的操作了.... html结构上合并了 但是dataSource还是同样的数组, 拉到下面就会被刷掉的.
#15

**Comment by ttjimsen** [comment]
> 不要在虚拟列表中做合并单元格的操作了.... html结构上合并了但是dataSource还是同样的数组，拉到下面就会被刷掉的。
> [＃15](https://github.com/crawler-django/virtuallist-antd/issues/15)

好吧，后续有没有可能兼容合并呢？
