### ISSUE TITLE
使用antd Table sticky属性时，滚动时渲染有时会有空白。

### ISSUE THREAD

**Issue by mar105** [crawler-django/virtuallist-antd#23]
使用antd Table sticky属性时，滚动时有时会有空白。
增加body 行拖拽代码后，渲染滚动条异常。

**Comment by crawler-django** [comment]
https://codesandbox.io/s/vibrant-darkness-kvt56?file=/index.js.
我猜原因可能是你的scrolly没有传值, 所以你的Table没有出现滚动条, 而是body出的.

**Comment by crawler-django** [comment]
我后面试试能不能兼容来一个getScrollContainer吧

**Comment by crawler-django** [comment]
你想要sticky的效果 你不妨把scrolly 和 VList的height的值调大一点.

**Comment by crawler-django** [comment]
至于行拖拽  antd官方展示的那些把VList的body.row给覆盖了. 所以会出现问题.  具体解决方案还待思考

**Comment by mar105** [comment]
使用antd Table sticky属性时，滚动时有时会有空白。  我看你的例子是不会，我scoll y传了500，height500 不加 sticky都正常，加了后偶尔会有一次没渲染全，先不管了，我再找找是不是我传了其他属性的原因。

**Comment by crawler-django** [comment]
行拖拽例子: https://codesandbox.io/s/drag-row-1fjg4?file=/index.js

**Comment by mar105** [comment]
非常感谢，测试了没有问题。

**Comment by crawler-django** [comment]
0.5.7-beta.1有点问题, 要升级到0.5.7,

**Comment by mar105** [comment]
好的，我升级一下。

**Comment by mar105** [comment]
行拖拽 影响到了antd官方的拖拽手柄列。以前可用。

**Comment by crawler-django** [comment]
不会有问题啊.. 例子: https://codesandbox.io/s/tuozhuaishoubinglie-antd4156-forked-1d6z1?file=/index.js
VWrapper 和 VRow代替一下tbody 和 tr就好了
