### ISSUE TITLE
滚动条处罚底部请求API函数,在Electron环境中没有执行？

### ISSUE THREAD

**Issue by yangjiaqiao** [crawler-django/virtuallist-antd#24]
滚动条处罚底部请求API函数 **onReachEnd** ，在Electron中没有执行而 **onScroll** 在Electron环境中可以执行，在浏览器中没有问题，请问 **onReachEnd** 是采用什么方式返回的呢？请问是什么问题导致的呢？使用 **react-infinite-scroller**  在Electron中执行没有问题。

**Comment by crawler-django** [comment]
我在electron环境测试了并没有问题啊, 你可以简单的搭个cra和electron, 使用例子上的代码试试.

例子上的代码是可以跑的.
或者你可以有重现的例子吗?

**Comment by crawler-django** [comment]
我测试的环境:  electron@12.0.9 react@17.0.2 antd@4.15.6 virtuallist-antd@0.5.7

**Comment by yangjiaqiao** [comment]
现在莫名其妙的又可以了，谢谢

crawler-django ***@***.***>于2021年5月24日 周一上午9:37写道：

**Comment by crawler-django** [comment]
唯一有可能出现的问题就是:  滚动的太快了, 节流60ms都赶不上滚动的手速, 这时候就会出现没有加载数据的情况. (不过此时再向上滑一下滚动, 再滚动一下就好了)

讲道理, 60ms应该够了吧....
