### ISSUE TITLE
滚动加载onReachEnd,在滚动条在底部的时候，执行了两次

### ISSUE THREAD

**Issue by yangjiaqiao** [crawler-django/virtuallist-antd#26]
滚动加载onReachEnd,在滚动条在底部的时候，执行了两次，是滚动高度设置的问题吗？

**Comment by crawler-django** [comment]
可以提供重现例子吗? 我测试打印都是没什么问题的.

**Comment by yangjiaqiao** [comment]
> 可以提供重现例子吗? 我测试打印都是没什么问题的.

谢谢，这边已经没有出现了，可能是数据加载的问题
