### ISSUE TITLE
在codesandbox下使用下面这段代码，scrollTo有问题。

### ISSUE THREAD

**Issue by mar105** [crawler-django/virtuallist-antd#27]
import React, { useState, useEffect } from "react";
import { render } from "react-dom";
import { Table, Input, Button } from "antd";
import { VList, scrollTo } from "virtuallist-antd";

import "./styles.css";
import "antd/dist/antd.css";

function App() {
  const [dataSource, setDataSource] = useState([]);

  useEffect(() => {
    let tempDataSource = [];
    for (let i = 0; i < 1000; i++) {
      tempDataSource.push({
        company_name: `aaa${i} 富士山下的你好美 你知道吗`,
        company_name1: `aaa${i} index index index index`,
        company_name2: `aaa${i} company index index index`,

        company_name3: `aaa${i} company company index index`,
        company_name4: `aaa${i} company company company index`,
        company_name5: `aaa${i} company company company company`,
        company_name6: `aaa${i} company index index company`
      });
    }

    setTimeout(() => {
      setDataSource(tempDataSource);
    }, 2000);
  }, []);

  const columns = [
    {
      title: "序号",
      key: "id",
      fixed: "left",
      render(text, record, index) {
        return index + 1;
      },
      width: 100
    },
    {
      title: "公司",
      dataIndex: "company_name",
      render(text, record, index) {
        return <Input value={text} />
      },
      width: 200
    },
    {
      title: "公司1",
      dataIndex: "company_name1",
      render(text, record, index) {
        return <Input value={text} />
      },
      width: 200
    },
    {
      title: "公司2",
      dataIndex: "company_name2",
      render(text, record, index) {
        return <Input value={text} />
      },
      width: 200
    }
  ];

  return (
    <>
      <Button style={{ marginRight: 10 }} onClick={() => {
        const tmpdataSource = [...dataSource];
        tmpdataSource.push({company_name6: `aaa${tmpdataSource.length + 1} company index index company`});
        setDataSource(tmpdataSource);
        scrollTo({ row: tmpdataSource.length })
      }
      }>
        scrollTo row: 30
      </Button>
      <Button onClick={() => scrollTo({ y: 1000 })}>scrollTo y: 1000</Button>
      <Table
        columns={columns}
        dataSource={dataSource}
        pagination={false}
        scroll={{ y: 500 }}
        rowKey={"company_name"}
        components={VList({
          height: 500
        })}
      />
    </>
  );
}

const rootElement = document.getElementById("root");
render(<App />, rootElement);

**Comment by mar105** [comment]
使用sticky属性就会有渲染空白的情况。

**Comment by crawler-django** [comment]
你把codesandbox的重现例子链接发我吧 你这让人看的很难受. 而且代码还不用```

**Comment by crawler-django** [comment]
你后面添加的是company_name6啊, columns字段没有company_name6. 肯定有空白行啊.
而且你scrollTo的row也不对,  应该是tmpdataSource.length - 1.
再者, 将scrollTo包裹在setTimeout里面.

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/119425356-c1f86880-bd39-11eb-9be1-e78db3a923a0.png)
这样子

**Comment by mar105** [comment]
https://codesandbox.io/s/musing-lalande-podlz?file=/src/App.tsx
我是拿的你的scrollTo的例子修改的，发现加了settimeout是可以了，有其他问题
1、没定位到最后，差一点点才到底。
2、还有一个就是闪动。
3、多点几下那按钮后，空白。

**Comment by mar105** [comment]
![image](https://user-images.githubusercontent.com/30144685/119451296-a73ce880-bd67-11eb-9b57-ee98e25c88ad.png)

**Comment by crawler-django** [comment]
你上面的链接demo没有问题啊.

**Comment by crawler-django** [comment]
用鼠标快速拖动滚动条的时候是有点问题, 用滚轮就没问题. 我测测是不是节流的问题.
但这不是scrollTo的问题啊

**Comment by mar105** [comment]
我定位最后一条，scrollto没精准定位到最后一条，差一点点。
多点几下按钮空白。不知道是不是也是你那节流的问题。
用滚轮出现的几率少，滚快了，偶尔就有一次。

**Comment by crawler-django** [comment]
升级到v0.5.8, 就没有空白问题和距离问题了.

至于闪动, 添加onReachEnd就可以了.  如: VList({ height: 500, onReachEnd: () => {} })

**Comment by mar105** [comment]
升级了是可以了，就是滚动的时候会有空白，停下时是可以的，现在不影响界面了。 滚动到最后一条，我测试只要滚动条在最下面添加数据没有问题，定位精准。不闪动。滚动条在上面时添加一条数据滚动到最后一条，定位不精准，会有闪动。
之前sticky这个会影响空白，你这次改动也不影响了。
onReachEnd我现在是加载数据时用的。不知道闪动为什么会用到这个？大神可指点下。

**Comment by crawler-django** [comment]
滚动有空白是正常的啊, 滚动会加载数据, 结构越复杂加载的就慢咯.

闪动会用onReachEnd的问题, 主要是查询数据/分页后, 数据会变更, 此时我会将scrollTop置为0, 让滚动条回归顶部.
你那个例子是数据变更了, 还要滚动条在底部.  
我那边又有个逻辑, 拥有onReachEnd的话就不会将scrollTop置为0. 不置为0就不会有上下闪动的情况了.
