### ISSUE TITLE
请问一下，在使用路由缓存插件umi-plugin-keep-alive后，无法对列表进行数据的渲染。

### ISSUE THREAD

**Issue by yangjiaqiao** [crawler-django/virtuallist-antd#28]
在项目中增加路由缓存插件 **umi-plugin-keep-alive** ，显示数据的时候，无法渲染全部数据，只是渲染第一条数据就不渲染其他的数据了。采用 **KeepAlive** 对组件进行包裹。
代码：
![image](https://user-images.githubusercontent.com/51978469/119691937-91b9e280-be7d-11eb-8614-42ca2a46c608.png)
请求数据:
![image](https://user-images.githubusercontent.com/51978469/119692157-c168ea80-be7d-11eb-8d96-52b26d781559.png)
渲染效果图（不加 **KeepAlive**）：
![image](https://user-images.githubusercontent.com/51978469/119692418-f70dd380-be7d-11eb-9fdb-1abb3ef64639.png)
增加 **KeepAlive** 后效果
![image](https://user-images.githubusercontent.com/51978469/119692536-0f7dee00-be7e-11eb-969f-782f941184a4.png)

**Comment by crawler-django** [comment]
你给你的HztStyleTable再包裹一层试试?
我用react-activation写个demo都没问题.
![image](https://user-images.githubusercontent.com/37062307/119752148-08330080-becf-11eb-8823-88639be7b8d0.png)

**Comment by yangjiaqiao** [comment]
> 你给你的HztStyleTable再包裹一层试试?
> 我用react-activation写个demo都没问题.
> ![image](https://user-images.githubusercontent.com/37062307/119752148-08330080-becf-11eb-8823-88639be7b8d0.png)

在HztStyleTable上面包裹也是一样的效果

**Comment by yangjiaqiao** [comment]
> > 你给你的HztStyleTable再包裹一层试试?
> > 我用react-activation写个demo都没问题.
> > ![image](https://user-images.githubusercontent.com/37062307/119752148-08330080-becf-11eb-8823-88639be7b8d0.png)
> 
> 在HztStyleTable上面包裹也是一样的效果
HztStyleTable 是一个样式组件

**Comment by crawler-django** [comment]
不是简单的写上<div><HztStyleTable /></div>哦, KeepAlive要将它的数据逻辑层也包裹起来.
我是重现不了你说的问题, 要不然你使用react-activation试试?

**Comment by yangjiaqiao** [comment]
好的，谢谢


crawler-django ***@***.***>于2021年5月27日 周四下午5:56写道：
