### ISSUE TITLE
列宽无法限制

### ISSUE THREAD

**Issue by ttjimsen** [crawler-django/virtuallist-antd#30]
请问在ant table里设置了列宽，为什么会失效，不受控

**Comment by crawler-django** [comment]
给个复现demo

**Comment by crawler-django** [comment]
如果不是因为虚拟列表导致的问题, 没有虚拟列表也会这样的话.  建议转到antd的issue

**Comment by ttjimsen** [comment]
好的，谢谢，我看下原因， 请问是否支持proTable？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crawler-django/virtuallist-antd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crawler-django/virtuallist-antd] 列宽无法限制 (#30)





 
如果不是因为虚拟列表导致的问题, 没有虚拟列表也会这样的话.  建议转到antd的issue

**Comment by crawler-django** [comment]
能用就可以支持, 只要proTable没改rc-table的components, 基本都没问题

**Comment by ttjimsen** [comment]
好的，谢谢，protable渲染多数据有坑，git提issue直接让我去看table的虚拟滚动，项目都快结束了，真心累



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月18日(周五) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.******@***.***&gt;;
主题: Re: [crawler-django/virtuallist-antd] 列宽无法限制 (#30)




 
能用就可以支持, 只要proTable没改rc-table的components, 基本都没问题

**Comment by ttjimsen** [comment]
大佬 强制限定了ellipsis: true？   项目需求不要缩略。该如何处理呢？

**Comment by ttjimsen** [comment]
大佬 强制限定了ellipsis: true？  我试了ellipsis: false无效  项目需求不要缩略。该如何处理呢？（基于ant Table）

**Comment by crawler-django** [comment]
调大点宽度咯..  没有ellpsis没法固定每行的高度------------------&nbsp;原始邮件&nbsp;------------------
***@***.******@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crawler-django/virtuallist-antd] 列宽无法限制 (#30)

**Comment by crawler-django** [comment]
还可以加个详情框 点开来看咯  方法总是多的------------------&nbsp;原始邮件&nbsp;------------------
***@***.******@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crawler-django/virtuallist-antd] 列宽无法限制 (#30)

**Comment by ttjimsen** [comment]
求问，要实现虚拟滚动是否必须要限定行高？

**Comment by crawler-django** [comment]
你有好的方法处理不同行高吗？ 欢迎pr------------------&nbsp;原始邮件&nbsp;------------------
***@***.******@***.***&gt;
发送时间:&nbsp;2021年6月19日(星期六) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crawler-django/virtuallist-antd] 列宽无法限制 (#30)

**Comment by ttjimsen** [comment]
给我一个答复，让产品死心  哈哈

**Comment by daiguadaidai** [comment]
> 

同问, 请问找到答案了么

**Comment by seallard** [comment]
It would be really nice to support variable row heights to let text overflow. But I guess it is difficult to make the virtualization efficient if you allow variable row heights.
