### ISSUE TITLE
单元格宽度无法超出隐藏

### ISSUE THREAD

**Issue by arlen977** [crawler-django/virtuallist-antd#32]
自定义的宽度无效，始终会根据内容自动撑开，无法超出隐藏

**Comment by crawler-django** [comment]
提供一下重现demo

**Comment by arlen977** [comment]
> 提供一下重现demo

找到原因了，x设置 max-content就会有这种问题

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/124855204-341bc880-dfdb-11eb-9f84-88dc51bc002c.png)
https://github.com/ant-design/ant-design/issues/28927
