### ISSUE TITLE
如何兼容自定义的Table components？

### ISSUE THREAD

**Issue by alienzhangyw** [crawler-django/virtuallist-antd#34]
我项目中自定义了components来实现表格的右键菜单：
``` ts
const wrapperRender = (props: any) => <Dropdown overlay={contextMenu} trigger={['contextMenu']}><tbody {...props} /></Dropdown>;
const components = {
  body: {
    wrapper: wrapperRender,
  },
}
```
Table参数 `components = {merge(VList({ height: tableHeight }), components)} // lodash/merge`

这样的话虚拟列表会出bug，往下滚动的时候永远只显示开头的十几条数据，但是内容高度却在无限增长，滚不到底。

**Comment by crawler-django** [comment]
不要覆盖VList的组件, 可以考虑包裹它. 比如你要替换wrapper, 就使用`<Dropdown>{VList({ height: 500 }).wrapper}</Dropdown> `这样子试试.

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/125426800-bde86bf1-d32b-4e49-be1b-35fb18e26078.png)
这4个都不建议覆盖, 可以使用高阶组件包裹的方式.
除开这些其他的都可以覆盖, 不如header

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/125428449-6e84cf3d-d2e2-40e4-9c64-4f26c8367d08.png)
![image](https://user-images.githubusercontent.com/37062307/125428500-50a46919-ef4a-4da3-a596-97f7dd599874.png)
可以参考https://github.com/crawler-django/virtuallist-antd/blob/master/docs/examples/DragRow.tsx

**Comment by alienzhangyw** [comment]
了解了，谢谢
