### ISSUE TITLE
使用antd tabs与table虚拟化发现的问题

### ISSUE THREAD

**Issue by SamWeichangyue** [crawler-django/virtuallist-antd#37]
antd：4.9.0
react：17.0.1
react-dom：17.0.1
virtuallist-antd：0.5.8
场景：tab2页签使用table虚拟化，切换到tab2后，请求后端数据，loading5秒，在loading间切换至tab1页签，等待5秒后再切回至tab2页签。虚拟列表只渲染一条数据

https://codesandbox.io/embed/determined-wind-hh52q?fontsize=14&hidenavigation=1&theme=dark

**Comment by SamWeichangyue** [comment]
目测问题应该是: 由于tabs 切换会将 原来的tabs样式添加display:none样式，导致获取第一行元素高度为0，无法渲染

**Comment by crawler-django** [comment]
嗯 父节点display: none导致子节点获取不到真实的高度, 子节点的offsetHeight都为0, 所以就会出现问题.

**Comment by crawler-django** [comment]
有个很简单的处理方法: 你请求到的dataSource先存起来, 比如存到tData里, 等tabKey === '2'的时候, 再把tData赋值给dataSource不就行了。

**Comment by SamWeichangyue** [comment]
找到个骚操作，修改tabPane的样式，改为style={activeKey === "2" ? {} : {visibility: "hidden", display: "block"}}
当然这不用写其他兼容性代码了，也只适用部分场景

**Comment by qqe241241** [comment]
有个方法，重新渲染一下表格好像也可以
