### ISSUE TITLE
不知能否加入当数据不超过一屏时不显示滚动条的功能

### ISSUE THREAD

**Issue by carrymaniac** [crawler-django/virtuallist-antd#38]
在配置使用VList之后，当我的数据量不多的时候，页面右侧也会显示滚动条，想问问大佬能否加入判断不超过一屏时不显示滚动条的功能（类似antd官方给的虚拟化列表的示例）？或者是有没有什么思路可以提供一下 感谢
![image](https://user-images.githubusercontent.com/30337438/130172614-fa1f7aa7-3831-4bb3-8976-f415becb8334.png)

**Comment by crawler-django** [comment]
提供一下复现demo.
下面例子没有什么问题啊, 我这边一屏没有出现滚动条啊
https://codesandbox.io/s/trusting-nightingale-2t81h?file=/src/index.tsx

**Comment by carrymaniac** [comment]
不好意思说的不够准确 我指的就是如图所指的滚动条面板(轨道) scrollbar-track
![image](https://user-images.githubusercontent.com/30337438/130175393-29a348aa-2757-4c24-873c-bf0eec6142c8.png)
在我们的项目中表现形式就是右侧固定出现这样的滚动条面板 
期待的效果是和设置了overflow:auto一样 如果不超过一屏 则不显示滚动条面板
像一开始贴的antd官方例子一样 数据少的时候 右侧不出现这个面板

**Comment by crawler-django** [comment]
这个不是虚拟列表插件的问题.
是antd-table的问题, 你设置了scrolly, 它对应的overflow就是scroll.
https://codesandbox.io/s/trusting-nightingale-2t81h?file=/src/index.tsx

可以去antd那里提issue
