### ISSUE TITLE
使用可编辑单元格功能时， table表格就只展示一列

### ISSUE THREAD

**Issue by becca-ch** [crawler-django/virtuallist-antd#39]
1. body 加上 row: EditableRow 使用虚拟列表就只展示一行， 注释掉则编辑单元格功能就不能用了
 const VComponents = VList({ height: 500 });

    const components = {
      ...VComponents,
      body: {
        ...VComponents.body,
        cell: EditableCell,
        row: EditableRow,
      },
    };

案例地址
https://codesandbox.io/s/vigilant-frost-8vhuq?file=/src/App.js

**Comment by crawler-django** [comment]
EditableRow替换掉了VComponents.body.row.
EditableCell也替换掉了VComponents.body.cell.
你把VComponents.body.row嵌进EditableRow就行了. 同理cell也一样.

![image](https://user-images.githubusercontent.com/37062307/131481606-b3763fee-5130-47f3-ad82-1d057c04c0b2.png)
![image](https://user-images.githubusercontent.com/37062307/131481717-d73b0d11-8765-439a-aeed-dafaffc8a572.png)

**Comment by becca-ch** [comment]
可以了 感谢大大
