### ISSUE TITLE
1. 选择多条数据时，数据不完整 2. 树形表格bug

### ISSUE THREAD

**Issue by hejinhua** [crawler-django/virtuallist-antd#4]
1. selectedRows里面只有最后一条数据是完整的，其他的数据都会缺少字段
这是选中的数据
![image](https://user-images.githubusercontent.com/39826101/79738184-004d7800-832f-11ea-9a32-a9be8b35532c.png)
这是打印的selectedRows
![image](https://user-images.githubusercontent.com/39826101/79738198-07748600-832f-11ea-9012-b14680c4a2f5.png)
2. 树形表格初始只有一个节点时，打开之后滚动会白屏

**Comment by crawler-django** [comment]
现在的代码对树形结构的数据是不友好的. 可以说暂时不支持树形结构, 这个点我会抽空去思考处理一下. 

然后关于选择多条数据的时候, 数据不完整. 需要你提现复现demo(树形结构的除外), 我自己用是没有问题的. 多选不是可以通过rowSelections来获取selectedRows吗?

**Comment by hejinhua** [comment]
排查了一遍代码，选择数据不完整发现是我自己的代码bug，谢谢了

**Comment by crawler-django** [comment]
我再次研究了下rc-table现在的源码, rc-table处理树形结构数据的时候 是用递归来处理的, 不是先将数组扁平化来处理的. (在dom上查看代码 trs是扁平化的结构, 但是代码上没有进行扁平化的处理. 没有做哪些是点击的 需要展示的, 统一放到一个数组里.)   

![image](https://user-images.githubusercontent.com/37062307/80083975-d2fc0680-8588-11ea-9a3e-231b60deb9f4.png)

毕竟虚拟列表的本质 是渲染一定的个数, VWrapper上获取的数据不是扁平化的数据, 就很难做到树形结构数据的虚拟滚动. (在如今rc-table里应该是做不到, 除非后续有变动. 我也翻阅了下其他树形结构虚拟滚动的处理, 都是把数据扁平化了的 )

总而言之, 依赖于如今rc-table版本的本组件, 暂时不会支持树形结构.
