### ISSUE TITLE
展开树形表格，再重新加载数据，不能完全展示新加载的数据

### ISSUE THREAD

**Issue by ConanZZ** [crawler-django/virtuallist-antd#48]
文字描述不如看demo更清楚，复现步骤是：先点击一下send按钮加载数据，再将第一行数据的树形表格全部打开，之后再点击一下send按钮重新加载数据，新加载的第二个数据没展示出来。跟antd的table行为不一致

复现链接： https://codesandbox.io/s/shu-xing-biao-ge-forked-b67hn

**Comment by crawler-django** [comment]
试试 v0.6.4-beta.0

**Comment by crawler-django** [comment]
https://codesandbox.io/s/shu-xing-biao-ge-forked-l3c1t?file=/src/index.tsx

**Comment by ConanZZ** [comment]
这个问题升级包至 v0.6.4-beta.0 已解决，感谢
