### ISSUE TITLE
使用table的expandable属性时，虚拟表格不能按预期展开，且滚动条位置错误

### ISSUE THREAD

**Issue by ConanZZ** [crawler-django/virtuallist-antd#52]
https://codesandbox.io/s/shu-xing-biao-ge-forked-b67hn?file=/src/index.tsx:3539-3546
复现步骤：
        不能按预期展开：点击send按钮，点击展开，树形表格没有按预期展开，与antd的Table表现不一致；
        滚动条位置错误：展开表格后，将滚动条滚动至表格底部，将table3对应的权限由“读写”改为“只读”后，滚动条直接滚动到表格顶部，预期滚动条的位置不动，这里与antd的Table表现不一致。

**Comment by crawler-django** [comment]
不支持expandable, expandable展开的高度不应该被限制死

**Comment by crawler-django** [comment]
之前理解错你的意思了.
你用useMemo把VList包起来就行了
https://codesandbox.io/s/shu-xing-biao-ge-forked-268ot

**Comment by ConanZZ** [comment]
> 之前理解错你的意思了. 你用useMemo把VList包起来就行了 https://codesandbox.io/s/shu-xing-biao-ge-forked-268ot

嗯嗯，感谢大佬，用useMemo包起来可以解决展开的问题。但是改变数据之后，预期的滚动条的位置也应该是不变的，复现：在demo [https://codesandbox.io/s/shu-xing-biao-ge-forked-268ot] 里将table3对应的权限由“读写”改为“只读”后，滚动条直接滚动到表格顶部，并且scroll的高度也变了。

**Comment by ConanZZ** [comment]
更清楚的demo在这：https://codesandbox.io/s/shu-xing-biao-ge-forked-div95?file=/src/index.tsx
点击send填充数据，然后展开树形表格，将滚动条滚动至表格底部，改变最后一条数据权限列的Select的值，然后滚动条会滚动至表格底部，然后虚拟表格的scroll高度就变了。

**Comment by crawler-django** [comment]
不想变化的话, 可以添加新的属性
![image](https://user-images.githubusercontent.com/37062307/145928434-8febc8ed-4348-4a15-8e53-5e31180341a6.png)

如果要根据你自己喜好来决定他变不变的话,  可以将它变成可控属性

**Comment by ConanZZ** [comment]
> 不想变化的话, 可以添加新的属性. 要v0.7.0 ![image](https://user-images.githubusercontent.com/37062307/145928434-8febc8ed-4348-4a15-8e53-5e31180341a6.png)
> 
> 如果要根据你自己喜好来决定他变不变的话, 可以将它变成可控属性

https://codesandbox.io/s/shu-xing-biao-ge-forked-div95?file=/src/index.tsx
每次改变select的值，table的高度会变化，而且随着滚动一直在抖动。

**Comment by ConanZZ** [comment]
![动画](https://user-images.githubusercontent.com/19329479/145951636-2168aa66-b591-499b-90a9-90bad1f37290.gif)

**Comment by crawler-django** [comment]
v0.7.1 没问题了

**Comment by alextaymx** [comment]
v0.7.2 遇到类似的问题， 请问如何在expandable属性：expand=true 时扩大高度

**Comment by alextaymx** [comment]
https://codesandbox.io/s/reachend-wu-xian-jia-zai-xu-ni-gun-dong-forked-bib6cz

**Comment by crawler-django** [comment]
目前只能支持树形的展开. 你的demo没有更新

**Comment by alextaymx** [comment]
我这边用的是0.7.2 ， sandbox忘了更新，所以目前这类型的展开是不支持的对吗？
