### ISSUE TITLE
当第二次加载的数据为空数组时，table的高度不是预期中的auto而是根据第一次加载的数据行高来计算

### ISSUE THREAD

**Issue by ConanZZ** [crawler-django/virtuallist-antd#53]
demo: https://codesandbox.io/s/shu-xing-biao-ge-forked-div95?file=/src/index.tsx:581-593

复现：先点击send加载数据，不展开，再点击一次send加载空数据；或先点击send加载数据，展开数据，再点击一次send加载空数据。
与antd Table表现不一致，预期空状态时高度为auto，完全展示出来，不需要scroll。

**Comment by crawler-django** [comment]
这个0.7.1也解决了
