### ISSUE TITLE
dataSource 改变后  滚动条回到了顶部

### ISSUE THREAD

**Issue by meikang123** [crawler-django/virtuallist-antd#54]

**Comment by crawler-django** [comment]
正常是会回滚到顶部的. 不想回滚的话将resetTopWhenDataChange改为false

![image](https://user-images.githubusercontent.com/37062307/146324285-2c1db4b3-eede-458d-957c-8a744d7ae9cb.png)

**Comment by meikang123** [comment]
> 

看了类型声明没有  果然可以  还有一个问题 我height设置calc(100vh -300px)后  如果F12调试的时候 打开  就不能放大了

**Comment by crawler-django** [comment]
你想表达的是高度问题?
这个应该不是插件的问题, 你的高度变了但你没有告知插件高度变了

**Comment by meikang123** [comment]
![image](https://user-images.githubusercontent.com/16129828/146335415-b12d2fd5-d3c8-439b-b646-36248c9cb8e4.png)
拖拽元素都隐藏了

**Comment by crawler-django** [comment]
放大是什么意思  给个demo

**Comment by meikang123** [comment]
https://codesandbox.io/s/loving-chebyshev-miccg

**Comment by meikang123** [comment]
有参数可以设置预渲染列表吗

**Comment by meikang123** [comment]
![image](https://user-images.githubusercontent.com/16129828/146399692-9eb228d0-5063-4c13-9186-cde968510e33.png)
需要一个index  才不会空白

**Comment by crawler-django** [comment]
![image](https://user-images.githubusercontent.com/37062307/146472312-bd4f3a60-dbc5-4513-bca5-da16dba1b9e3.png)

因为你这里写的就是要index啊

**Comment by youngList** [comment]
遇到一个加了属性resetTopWhenDataChange依然跳回去的，示例链接 https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-6wwiqs?file=/demo.js

**Comment by crawler-django** [comment]
> https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-6wwiqs?file=/demo.js

用useMemo包裹VList就好了

**Comment by youngList** [comment]
> > https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-6wwiqs?file=/demo.js
> 
> 用useMemo包裹VList就好了

感谢大佬

**Comment by weizheweng** [comment]
> > https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-6wwiqs?file=/demo.js
> 
> 用useMemo包裹VList就好了

请问大佬，如果是使用Class Component的话，该怎么写???

**Comment by YDJSZY** [comment]
> 正常是会回滚到顶部的. 不想回滚的话将resetTopWhenDataChange改为false
> 
> ![image](https://user-images.githubusercontent.com/37062307/146324285-2c1db4b3-eede-458d-957c-8a744d7ae9cb.png)

无效

**Comment by YDJSZY** [comment]
> > https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-6wwiqs?file=/demo.js
> 
> 用useMemo包裹VList就好了

也不行
