### ISSUE TITLE
表格数据重新加载后，有时候会在头几行出现上一次查询的数据

### ISSUE THREAD

**Issue by alienzhangyw** [crawler-django/virtuallist-antd#55]
偶现，无法确定触发的原因。
![image](https://user-images.githubusercontent.com/58874541/157795217-4b1729b2-94e6-4f62-82d2-092820d20b8b.png)
如果新的查询结果为空，还可能出现上一次查询的某一行一直不断重复，滚动条永远拉不到底的情况。

**Comment by crawler-django** [comment]
我这边项目基本没有出过这个问题哦 是0.7.2的版本吗

**Comment by crawler-django** [comment]
给个antd的版本 和 virtuallist-antd的版本

**Comment by crawler-django** [comment]
当前的一个页面是否有多个virtual table同时存在?

如果没有同时存在的话, virtuallist-antd的插件只是对VWrapper接收的现有数据的裁剪, 讲道理不会有以前的数据啊, 这数据返回插件这边不会更改的

**Comment by alienzhangyw** [comment]
> 给个antd的版本 和 virtuallist-antd的版本

antd@4.18.3 virtualist-antd@0.7.2


> 当前的一个页面是否有多个virtual table同时存在?

有2个table，但是内容不一样，这个是在Modal弹窗里的

**Comment by alienzhangyw** [comment]
会不会是数据更新的时候，以前一些没显示在页面上但是dom里有的行没有被卸载干净？

**Comment by crawler-django** [comment]
> 会不会是数据更新的时候，以前一些没显示在页面上但是dom里有的行没有被卸载干净？

应该不是  我怀疑是两个virtual table的变量冲突了.
你在弹窗外的virtual table添加一个唯一的vid应该就没问题了.
有问题的话再排查

**Comment by alienzhangyw** [comment]
> > 会不会是数据更新的时候，以前一些没显示在页面上但是dom里有的行没有被卸载干净？
> 
> 应该不是 我怀疑是两个virtual table的变量冲突了. 你在弹窗外的virtual table添加一个唯一的vid应该就没问题了. 有问题的话再排查

但是两个表格的列内容完全不一样啊。我先加个vid试试。主要这些问题都是测试人员操作出来的，我自己复现不出来。

**Comment by crawler-django** [comment]
> > > 会不会是数据更新的时候，以前一些没显示在页面上但是dom里有的行没有被卸载干净？
> > 
> > 
> > 应该不是 我怀疑是两个virtual table的变量冲突了. 你在弹窗外的virtual table添加一个唯一的vid应该就没问题了. 有问题的话再排查
> 
> 但是两个表格的列内容完全不一样啊。我已经写了不一样的vid了。主要这些问题都是测试人员操作出来的，我自己复现不出来。

我也复现不出来 看看测试的具体操作...

**Comment by alienzhangyw** [comment]
> 是你的rowkey不唯一导致的。

那估计是因为后端返回的数据有问题，我rowkey用的是其中一列数据，按道理不应该重复的。
