### ISSUE TITLE
Editable rows and cells example

### ISSUE THREAD

**Issue by balboFK** [crawler-django/virtuallist-antd#56]
Hello @crawler-django, thanks again for the library!

Is there any way I could achieve the editable cells/row implementation using your library? I tried it in my local development but was unable to do it myself.

I tried using the default antd "Editable Cells" example: 
https://codesandbox.io/s/l9t5wc

If possible could you provide an example on how to do so? The example could also go to the docs like the many other you already have there, so it would help other people for future reference.

Thanks!

**Comment by crawler-django** [comment]
demo: https://codesandbox.io/s/editable-example-3656ln?file=/src/App.js
#39

i will provide this example in readme

**Comment by balboFK** [comment]
Thanks @crawler-django, awesome!
