### ISSUE TITLE
文本  white-space: nowrap;

### ISSUE THREAD

**Issue by xgAnd** [crawler-django/virtuallist-antd#58]
大佬  我看您这边的设置里面的所有div 都设置了 超出隐藏  我们现在有些情况文本超出需要换行显示 这样的动态高度计算是不是就存在问题了  如果这条数据没有出现在 首屏

**Comment by crawler-django** [comment]
现在不支持动态高度.
如果要动态高度的话, 最多只能跟react-window一样要开发者自己设置好全部高度.
#57

**Comment by xgAnd** [comment]
> 现在不支持动态高度. 如果要动态高度的话, 最多只能跟react-window一样要开发者自己设置好全部高度. #57

大佬请教个问题 我们现在在render的 div中 复写了white-space 为normal 看起来实现了所需的 动态高度 这个样子有什么坑吗 望大佬解惑

**Comment by crawler-django** [comment]
慢慢滚动那个多行数据的时候数据会跳动

**Comment by xgAnd** [comment]
> 慢慢滚动那个多行数据的时候数据会跳动

好的 多谢大佬解惑
