### ISSUE TITLE
Table scroll not working properly when using expandable property

### ISSUE THREAD

**Issue by balboFK** [crawler-django/virtuallist-antd#59]
Hello everyone!

I found an issue that when you have a expandable table with another table inside.
If you scroll to the last row of the table and expand it, the table scroll rolls back up a bit and you can't really see the content on the last row which was expanded.

I figured this out when my table got only 1 row of data and i tried to expand it, so the content would be visible, but when you scroll to it, the scroll behaves weirdly and looks like it's trying to go back up.

Sandbox with the reproducible issue:
https://codesandbox.io/s/sweet-sunset-rps1ho?file=/src/index.tsx

Any help would be appreciated.
Thanks.

**Comment by crawler-django** [comment]
only support tree table, other expandable table is not support

**Comment by crawler-django** [comment]
#52

**Comment by balboFK** [comment]
Do you plan on supporting expandable table too? 
Thanks!

**Comment by crawler-django** [comment]
It is very difficult,,,
it maybe solved when dynamic height table is achieved
now, dynamic height table.... no idea

**Comment by balboFK** [comment]
I see, is there any workarounds for now? I saw #52 as you said but i didn't see any solution either.
For now I think the best way is to use tree table as you recomended.

**Comment by crawler-django** [comment]
how about add a action?  it can show a detail modal.

**Comment by crawler-django** [comment]
There is no other good solution for no-tree expandable table

**Comment by balboFK** [comment]
@crawler-django the modal idea is very good, I might do it.
Thanks again!
