### ISSUE TITLE
表格中放input编辑更新数据，输入立即失焦

### ISSUE THREAD

**Issue by Petter-li** [crawler-django/virtuallist-antd#6]

**Comment by crawler-django** [comment]
demo: https://codesandbox.io/s/laughing-banach-4lo6m?file=/index.js
按这个例子来 没有这个问题.

**Comment by crawler-django** [comment]
demo: https://codesandbox.io/s/laughing-banach-4lo6m?file=/index.js
按这个例子来 没有这个问题.

**Comment by crawler-django** [comment]
把每页页数调到100条, 效果明显

**Comment by crawler-django** [comment]
如果你只是简单的放input, 不想像上面demo那个那样严谨。
你可以使用onBlur (失去焦点的时候才去更新值)  而不应该用onChange (使用onChange, 即使没有虚拟列表 输入也会很卡把).
不过onBlur 跟 虚拟列表结合有时候还是有点问题的. (在输入完了而且没失焦的时候, 进行了滚动就会导致重新渲染, 就会出现数据消失的情况.)

**Comment by Petter-li** [comment]
立即失焦的原因在于更改source之后，是重新返回的新的input，而不是更新input的值。我下载了源码，然后改了vlist的暴露方式，居然可以了。
const MemoV = useMemo(() => {
        return {
            table: VTable,
            body: {
                wrapper: VWrapper,
                row: VRow,
                cell: VCell
            }
        }
    }, [dataSource, columns, loading]);
不知道原因，但可行。如果大佬知道为什么的话，能讲讲不

**Comment by crawler-django** [comment]
如果这样可以, 你可以写成这样.
```
const MemoV = useMemo(() => {
    return {
        ...VList({
            height: 1000
        })
    }
}, [dataSource, columns])
```
如果不行, 可以方便给个demo地址吗?
