### ISSUE TITLE
虚拟列表中使用antdesign Input的失焦事件

### ISSUE THREAD

**Issue by xgAnd** [crawler-django/virtuallist-antd#63]
我们的列表数据没有分页，使用虚拟列表发现个问题就是Input在聚焦时滚动到不可见时 失焦不会触发Input的onBlur事件  在没使用虚拟列表之前是没有这个问题的。

**Comment by crawler-django** [comment]
这样的话, 你可以把你的input封装一层? 可以用useEffect return, 节点被清掉后再调用一次onBlur

**Comment by xgAnd** [comment]
> 这样的话, 你可以把你的input封装一层? 可以用useEffect return, 节点被清掉后再调用一次onBlur

大佬 我理解这样的话 即使我之前并没有聚焦也会调用这个onBlur 如果是的话 是不是还需要一套逻辑来判断之前是否聚焦过? 暂时在最后提交数据时对数据进行了兜底。

**Comment by crawler-django** [comment]
嗯 得有个记录当前是否正在聚焦的标记
