### ISSUE TITLE
React18开发环境下0.7.3版本滚动卡顿，出现白屏

### ISSUE THREAD

**Issue by alienzhangyw** [crawler-django/virtuallist-antd#68]
以前使用react17的时候性能正常，升级版本后发现此问题。
数据加载的时候会出现先渲染第一行，然后出现其他行的情况。
滚轮滚动时卡顿很明显，快速滚动会有白屏出现，CPU占用100%。
介绍里这个[简单的分页例子(easy pagination example)](https://codesandbox.io/s/gracious-resonance-tmw44)滚动时也会明显卡顿。

更新：只有开发环境会出现这个问题，生产环境不会卡顿。

**Comment by crawler-django** [comment]
会吗? https://codesandbox.io/s/gracious-resonance-tmw44
我这边依赖变更了 刷新一下 好像没有卡顿明显的问题呀

**Comment by alienzhangyw** [comment]
我过几天尝试搞个能复现的demo吧

**Comment by alienzhangyw** [comment]
我试了下，即使数据只有2列，依然会有卡顿，只是没那么严重，快速拖动滚动条依然会有零点几秒的白屏。但是Profiler里的渲染时间很短只有几十毫秒，查看浏览器的性能，发现finishConcurrentRender占用了很长的时间，如图：

**Comment by alienzhangyw** [comment]
https://codesandbox.io/s/dawn-thunder-j83e54?file=/src/index.tsx

**Comment by crawler-django** [comment]
https://codesandbox.io/s/reachend-wuxianjiazaixunigundong-y9nhd
你看看这个例子有明显卡顿吗?
我这边还算流畅啊. 只是快速滚动的时候出现少量空白而已. 也有可能是我机子性能好一点

**Comment by alienzhangyw** [comment]
> https://codesandbox.io/s/reachend-wuxianjiazaixunigundong-y9nhd 你看看这个例子有明显卡顿吗? 我这边还算流畅啊. 只是快速滚动的时候出现少量空白而已. 也有可能是我机子性能好一点

连续滚动两三次之后鼠标滚轮就失去响应几秒，这个我在antd官方例子上也会遇到，不知道是表格问题还是浏览器或者系统问题。拖动滚动条没问题。
