### ISSUE TITLE
console.log('销毁vid')

### ISSUE THREAD

**Issue by nichtsam** [crawler-django/virtuallist-antd#71]
這個console.log('销毁vid')是不是錯誤遺留的？

https://github.com/crawler-django/virtuallist-antd/blob/dc23b903d4481edca704cfebb219af476ddd5763/src/index.tsx#L210

**Comment by crawler-django** [comment]
不是  就调试的console.log

**Comment by nichtsam** [comment]
這樣會在production環境產生不被期待的log

**Comment by crawler-django** [comment]
晚上我会去掉log 再发布一个版本
