### ISSUE TITLE
固定列的样式和其他行没有对齐，使用过程中的3个bug

### ISSUE THREAD

**Issue by xiaoguo525** [crawler-django/virtuallist-antd#72]
**virtuallist-antd版本号：0.2.8**，**react版本号：16.8.6**
**1、浮动的操作栏的布局和其他列对不上**
![image](https://user-images.githubusercontent.com/39393904/184564365-11be2928-697c-431c-a38f-a0e5a84f4131.png)
**2、点击行内的展开后，滚动条会自动返回顶部**
**3、展开后的行在滚动过程中样式变形**
![123](https://user-images.githubusercontent.com/39393904/184567425-6b7a1b9f-0522-4489-b5a4-fd303a9c4b10.gif)

**Comment by xiaoguo525** [comment]
@crawler-django 帮忙看下以上问题要怎么改

**Comment by xiaoguo525** [comment]
![123](https://user-images.githubusercontent.com/39393904/184567865-e4fa9210-39a8-4c65-8e08-e85400b4582c.gif)

**Comment by crawler-django** [comment]
控件目前不支持展开expand.  只能支持树形表格的展开

**Comment by xiaoguo525** [comment]
> 

antd3升级antd4的问题多吗？
