### ISSUE TITLE
rerender 会引起自动 滚动到顶部

### ISSUE THREAD

**Issue by outNapGnaw** [crawler-django/virtuallist-antd#74]
版本: 0.7.4
现象：当滚动触发loading时，列表会自动滚动到顶部
[codesandbox](https://codesandbox.io/s/reachend-wu-xian-jia-zai-xu-ni-gun-dong-forked-9qn66f?file=/src/index.tsx)

**Comment by crawler-django** [comment]
https://codesandbox.io/s/reachend-wuxianjiazaixunigundong-y9nhd?file=/src/index.tsx 例子有问题吗

**Comment by crawler-django** [comment]
你的例子把loading作为依赖了肯定有问题呀.  怎么能将loading作为依赖呢

**Comment by outNapGnaw** [comment]
使用的场景就是这个handleReachEnd 内部也有其它的依赖
例子里面console.log(loading)是简化了一下

**Comment by crawler-django** [comment]
需要去除handleReachEnd的依赖, 这个函数变更会导致VList重新计算.  可以使用ref或者setXX(pre => ...) 去操作pre都行啊

**Comment by crawler-django** [comment]
让handleReachEnd尽量不要依赖于每次更新都会变更的参数
