### ISSUE TITLE
antd 4.12.0如何才能使用这个组件？

### ISSUE THREAD

**Issue by i3web** [crawler-django/virtuallist-antd#78]
文档上写着这个组件需要antd@4.17.0，但是项目的库是4.12.0,如果强行升级的话，会有很多样式以及错误要处理。
想问一下，这个4.12.0版本如何才能使用这个库？需要改动哪里？
或者说这个库用到了4.17.0哪个api？
非常感谢

**Comment by crawler-django** [comment]
有向下兼容.  只是需要树形虚拟表格的时候才要升级到4.17.0

**Comment by i3web** [comment]
> 有向下兼容. 只是需要树形虚拟表格的时候才要升级到4.17.0

对，我其实想问的是，如果我需要树形虚拟表格，4.12.0版本怎样才能使用这个库，源代码需要做怎样的改动？
目前项目中可能没办法一时半会儿升级到4.17.0

**Comment by crawler-django** [comment]
4.12.0用不了树形虚拟表格.  要求底层rc-table在7.20.4以上.
https://github.com/react-component/table

**Comment by i3web** [comment]
感谢。我看底层改动是将table树形结构的data进行了平铺，所以导致低版本的没法做虚拟滚动
