### ISSUE TITLE
批量删除数据，渲染丢失部分表格行

### ISSUE THREAD

**Issue by tomzio** [crawler-django/virtuallist-antd#83]
感谢作者提供的虚拟列表方案，在使用过程中发现了一些影响使用的问题：

问题重现步骤：
1. 表格中有两屏数据，可以滚动
2. 滑倒底部勾选后面的一半数据，批量删除
3. 此时表格上前几条数据丢失，state中数据是正常的

![批量删除前](https://user-images.githubusercontent.com/20125071/206354398-e55b3bb1-4a9b-4903-9236-aea6fc6c7e4e.png)
![批量删除后](https://user-images.githubusercontent.com/20125071/206354480-ecd85bf6-d196-4a77-a033-1f936876bcff.png)

感觉是前面的数据在表格划到底部后被虚拟列表移除，这时删除数据导致虚拟列表没有出现滚动条，之前被删除的行没有重新渲染。

**Comment by tomzio** [comment]
没问题了 数据变更时，监听dataSource重新渲染 VList 虚拟列表后解决了。

**Comment by crawler-django** [comment]
给个demo。 不想跳到第一行的话就用resetTopWhenDataChange

**Comment by tomzio** [comment]
这个是复现的demo
https://codesandbox.io/s/scrollto-forked-j6gx86

**Comment by crawler-django** [comment]
这样不是可以吗?  https://codesandbox.io/s/scrollto-forked-90owrp?file=/src/index.tsx

**Comment by crawler-django** [comment]
这样不是可以吗?  https://codesandbox.io/s/scrollto-forked-90owrp?file=/src/index.tsx

**Comment by crawler-django** [comment]
多使用使用hooks   你setDatasource 整个流程会重新跑的
