### ISSUE TITLE
表格行内高度动态改变后，scrollTo不准确了，怎样才能重新计算下呢？

### ISSUE THREAD

**Issue by luckyxutao** [crawler-django/virtuallist-antd#84]
表格行内高度动态改变后，scrollTo不准确了，怎样才能重新计算下呢？是不是能提供一个resize方法，谢谢

**Comment by crawler-django** [comment]
给个复现demo看看

**Comment by luckyxutao** [comment]
表格默认行高是60，切换模式后行高需要调成180， 两个模式来回切换
最新进展，通过设置不同vid可以解决
建议：有个方法或者重新计算行高就好了
这个组件还是很给力的，赞~

**Comment by whyour** [comment]
现在有方法或者重新计算行高吗
