### ISSUE TITLE
树形table，使用自定义展开节点，监听节点state时，滚动条会跳到顶部

### ISSUE THREAD

**Issue by RoarerWang** [crawler-django/virtuallist-antd#86]
https://codesandbox.io/s/quirky-lalande-3z0no0?file=/src/index.js

**Comment by crawler-django** [comment]
你的expandedRowKeys变化 整个vc都变化了  肯定会跳到顶部的. 为什么vc要监听expandedRowKeys的变化?

**Comment by RoarerWang** [comment]
table dataSource使用普通的变量时，滚动条会出现问题，监听expandedRowKeys可以解决，或者dataSource使用state也能解决。

**Comment by crawler-django** [comment]
一般来说 dataSource都是一个state,  dataSource变化说明表格需要重新渲染.  vc尽量不要任何依赖， 让它随表格渲染而重新渲染

**Comment by RoarerWang** [comment]
是的，现在我没有加监听值，不过树形table, 自定义展开节点，还会有个问题，expandedRowKeys改变后，sreollTo到指定行，这时，可能无法滚动到指定行，异步执行时可能会先滚动再展开，加定时器也无法解决，能否像antd树形结构那样滚动到指定的key呢。

**Comment by crawler-django** [comment]
试试v0.7.5-beta.2  我试了scrollTo是能正常运行的.
至于滚动到指定的key, 其实你都可以自己计算的.

**Comment by RoarerWang** [comment]
我现在就是自行计算的，会把默认要展开的父节点到要滚动到得节点间得行数计算出来。当父节点都是展开的情况下，会滚动到第一行正确的位置，但是如果是收起状态，我会同时改变expandedRowKeys，和要跳转得row,这时没有滚动到指定得行。
![image](https://user-images.githubusercontent.com/52812211/212328589-094a515a-505e-49e0-ad9e-278ac5448e16.png)

**Comment by RoarerWang** [comment]
![滚动问题](https://user-images.githubusercontent.com/52812211/212329678-271b967f-bc6c-4573-a634-8e57221355ac.gif)

**Comment by crawler-django** [comment]
你试试插件中新增的JumpTreeTable的demo

**Comment by RoarerWang** [comment]
我们两个得区别就是，我的定时器时间是50，调大点可能会好点

**Comment by FanFanFantastic** [comment]
> 一般来说 dataSource都是一个state, dataSource变化说明表格需要重新渲染. vc尽量不要任何依赖， 让它随表格渲染而重新渲染

thanks bro
