### ISSUE TITLE
树形 table，滑到底部，从底部开始往上收起，会出现空白

### ISSUE THREAD

**Issue by liuxy0551** [crawler-django/virtuallist-antd#87]
![2023-01-03 21 17 55](https://user-images.githubusercontent.com/34759874/210365345-a309272a-94db-4600-ab8a-95432f1f5138.gif)

从底部往上收起，假设最后一下收起后高度小于设置高度时，则此时的收起会让顶部元素不展示，[复现地址](https://stackblitz.com/edit/react-jau5de)，排查发现是下面的 if 忽略了上述情况：

``` ts
// 若totalLen小于renderLen, 说明一次就全部渲染完了, 不需要再dispatch
if (renderLen <= totalLen) {
    dispatch({
        type: 'changeTrs',
        curScrollTop: scrollTop,
    })
}
```

建议去除 if 判断，或者接收外部参数加一层控制

**Comment by RoarerWang** [comment]
我树形table，滚动条和你一样的问题，展开节点后，滚动条也会跳到顶部，有什么好的解决办法吗。

**Comment by crawler-django** [comment]
试试v0.7.5-beta.1
