### ISSUE TITLE
滚动到底部后，重新请求接口后数据量变少 不自动回到顶部，内容也不展示

### ISSUE THREAD

**Issue by luckyxutao** [crawler-django/virtuallist-antd#90]
对于批量删除、数量变少(滚动条与数据不匹配)会出现，谢谢

操作步骤：
1. 滚动到底部(在顶部无问题)
2. 点击删除

[demo](https://codesandbox.io/s/scrollto-forked-z5rzn6?file=/src/index.tsx)

**Comment by crawler-django** [comment]
试试v0.7.5-beta.1
