### ISSUE TITLE
scroll-x 失效  demo中也是失效的，什么原因？

### ISSUE THREAD

**Issue by ttjimsen** [crawler-django/virtuallist-antd#92]
![image](https://user-images.githubusercontent.com/31235202/215654549-c178c417-3e49-4cfe-9b2d-e1ecaa589f96.png)

**Comment by crawler-django** [comment]
你不使用VList scrollX会生效吗?

**Comment by crawler-django** [comment]
是overflow的问题 晚上修复

**Comment by Gowthamkosaraju** [comment]
Facing scroll-x issue. After adding columns more than screen width, table is not scrolling in x direction.
<img width="1355" alt="Screenshot 2023-01-31 at 10 10 23 PM" src="https://user-images.githubusercontent.com/5729762/215823965-cf822fe5-7b9d-4dca-8b77-2f742e756701.png">

**Comment by Gowthamkosaraju** [comment]
Thank you for quick fix. It's working now.
