### ISSUE TITLE
Problem when collapse

### ISSUE THREAD

**Issue by mmbfreitas** [crawler-django/virtuallist-antd#95]
Hello, I have a problem... when I close all the items being at the end of the list, the virtuallist does not load my first items and it has a blank space at the top, this only happens when you do it at the end of the list, could anyone help me?

![virtuallist](https://user-images.githubusercontent.com/7562414/224176396-a2fa9601-0ab0-4640-8e47-21c072464771.gif)

**Comment by crawler-django** [comment]
v0.7.6?  can u provide a demo?

**Comment by mmbfreitas** [comment]
i was using v0.7.4, it works after i updated, thanks
