### ISSUE TITLE
changeTotalLen action in VTable effect can sometimes return the wrong length. VWrapper effect seems more reliable

### ISSUE THREAD

**Issue by rmmanseau** [crawler-django/virtuallist-antd#97]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `virtuallist-antd@0.7.6` for the project I'm working on.

The effect that I removed in `function VTable` was causing issues when the parent of a component that uses VTable re-renders, and the table is displaying a hierarchy. the hierarchy i am using has 1 top level row with everything nested beneath, and because of the way that the antd table data prop is shaped, VTable thinks that there is only 1 row in the table. This causes it to issue the action `changeTotalLen` with length `1`. Generally this gets immediately overwritten by the effect in VWrapper, which has already processes the table data prop into a list of rows, and things work fine. But I ran into an edge case where the action in VTable gets run without the VWrapper effect getting run after. This resulted in the VList state saying that totalLen was 1, when it was actually much large. I solved the problem by commenting out the effect in VTable 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/virtuallist-antd/dist/index.es.js b/node_modules/virtuallist-antd/dist/index.es.js
index a172f55..68cf882 100644
@@ -788,18 +788,20 @@ function VTable(props, otherParams) {
         };
     }, [vid]);
     // 数据变更
-    useEffect(function () {
-        var _a, _b, _c, _d, _e, _f, _g;
-        ifChangeRef.current = true;
-        // console.log('数据变更')
-        if (isNumber((_c = (_b = (_a = children[1]) === null || _a === void 0 ? void 0 : _a.props) === null || _b === void 0 ? void 0 : _b.data) === null || _c === void 0 ? void 0 : _c.length)) {
-            dispatch({
-                type: 'changeTotalLen',
-                totalLen: (_g = (_f = (_e = (_d = children[1]) === null || _d === void 0 ? void 0 : _d.props) === null || _e === void 0 ? void 0 : _e.data) === null || _f === void 0 ? void 0 : _f.length) !== null && _g !== void 0 ? _g : 0,
-            });
-        }
-        // eslint-disable-next-line react-hooks/exhaustive-deps
-    }, [children[1].props.data]);
+
+    // useEffect(function () {
+    //     var _a, _b, _c, _d, _e, _f, _g;
+    //     ifChangeRef.current = true;
+    //     // console.log('数据变更')
+    //     if (isNumber((_c = (_b = (_a = children[1]) === null || _a === void 0 ? void 0 : _a.props) === null || _b === void 0 ? void 0 : _b.data) === null || _c === void 0 ? void 0 : _c.length)) {
+    //         dispatch({
+    //             type: 'changeTotalLen',
+    //             totalLen: (_g = (_f = (_e = (_d = children[1]) === null || _d === void 0 ? void 0 : _d.props) === null || _e === void 0 ? void 0 : _e.data) === null || _f === void 0 ? void 0 : _f.length) !== null && _g !== void 0 ? _g : 0,
+    //         });
+    //     }
+    //     // eslint-disable-next-line react-hooks/exhaustive-deps
+    // }, [children[1].props.data]);
+
     // table总高度
     var tableHeight = useMemo(function () {
         var temp = 'auto';
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by crawler-django** [comment]
thanks

**Comment by crawler-django** [comment]
v0.8.0-beta.1

**Comment by rmmanseau** [comment]
thanks!!
